### ISSUE TITLE
no config.yml

### ISSUE THREAD

**Issue by joex92** [TEXHIK/ReLoot#1]
How do I configure the plugin? 
how often are the chests relooted or are they only relooted when another player opens the chest?
are reloots per player only?

**Comment by TEXHIK** [comment]
There is nothing to configure for now. 
Each time a unique player opens chest it is generated as it do for the first time. Chest doess not regenerate by itself.
If you open the chest for the first time - it works like no one toched it before. If you already opened it, it is just a normal chest.
What do you mean "per player only"? There is no other reason to...

**Comment by joex92** [comment]
so by reloot you mean other players can reloot the chest but not that the chests will be refilled?

**Comment by TEXHIK** [comment]
> so by reloot you mean other players can reloot the chest but not that the chests will be refilled?

Yep. It's meant to be a solution for "Hey, I found a dungeon! Sadly, it has nothing, because I'm a 10th player, who found it", and not a source of infinite loot.
